"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

imgs=[]
for dirname, _, filenames in os.walk('app'):
    for filename in filenames:
        if filename not in ['.DS_Store','janipani.py']:
            imgs.append(os.path.join(dirname, filename))



APP = ['app/janipani.py']
DATA_FILES = ['app/janipani.py',*imgs]
OPTIONS = {'iconfile':'janipani.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
